import { NextResponse } from "next/server";
import {
  FBS_PERIODS,
  FCS_PERIODS,
  PERIOD_DEFINITIONS,
  formatPeriodRange,
  type PeriodType,
} from "@/lib/data/ncaa-calendar";

// Generate a RepMax-branded NCAA Recruiting Calendar PDF using raw PDF syntax
// No external PDF library needed — we construct the PDF manually

function escapeText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function generatePDF(division: "FBS" | "FCS"): Uint8Array {
  const periods = division === "FBS" ? FBS_PERIODS : FCS_PERIODS;
  const divLabel = division === "FBS" ? "Bowl Subdivision" : "Championship Subdivision";

  const periodTypeColors: Record<PeriodType, { r: number; g: number; b: number }> = {
    contact: { r: 0.22, g: 0.73, b: 0.44 },
    evaluation: { r: 0.24, g: 0.55, b: 0.87 },
    quiet: { r: 0.89, g: 0.75, b: 0.12 },
    dead: { r: 0.87, g: 0.33, b: 0.33 },
  };

  // Build page content
  let y = 750;
  const leftMargin = 50;
  const pageWidth = 512;
  let content = "";

  // RepMax Header
  content += `BT /F1 28 Tf ${leftMargin} ${y} Td (${escapeText("REPMAX")}) Tj ET\n`;
  content += `0.85 0.68 0.08 rg\n`; // Gold color
  content += `${leftMargin} ${y - 5} ${100} 3 re f\n`;
  content += `0 0 0 rg\n`;
  y -= 40;

  content += `BT /F1 18 Tf ${leftMargin} ${y} Td (${escapeText("2025-26 NCAA Recruiting Calendar")}) Tj ET\n`;
  y -= 25;
  content += `BT /F2 14 Tf ${leftMargin} ${y} Td (${escapeText(`Division I Football — ${divLabel}`)}) Tj ET\n`;
  y -= 18;
  content += `BT /F2 10 Tf 0.4 0.4 0.4 rg ${leftMargin} ${y} Td (${escapeText("Aug. 1, 2025 — July 31, 2026  |  repmax.io")}) Tj ET\n`;
  content += `0 0 0 rg\n`;
  y -= 30;

  // Separator line
  content += `0.8 0.8 0.8 RG 0.5 w ${leftMargin} ${y} m ${leftMargin + pageWidth} ${y} l S\n`;
  y -= 25;

  // Period Schedule Table
  content += `BT /F1 14 Tf ${leftMargin} ${y} Td (${escapeText("Recruiting Period Schedule")}) Tj ET\n`;
  y -= 20;

  // Table header
  content += `0.92 0.92 0.92 rg ${leftMargin} ${y - 4} ${pageWidth} 18 re f\n`;
  content += `0 0 0 rg\n`;
  content += `BT /F1 9 Tf ${leftMargin + 8} ${y} Td (${escapeText("DATES")}) Tj ET\n`;
  content += `BT /F1 9 Tf ${leftMargin + 260} ${y} Td (${escapeText("PERIOD TYPE")}) Tj ET\n`;
  y -= 22;

  for (const period of periods) {
    if (y < 80) break; // Page overflow protection

    const dateRange = formatPeriodRange(period.start, period.end);
    const color = periodTypeColors[period.type];
    const typeName = period.type.charAt(0).toUpperCase() + period.type.slice(1);

    // Color dot
    content += `${color.r} ${color.g} ${color.b} rg\n`;
    content += `${leftMargin + 260} ${y + 2} 8 10 re f\n`;
    content += `0 0 0 rg\n`;

    // Date range
    content += `BT /F2 9 Tf ${leftMargin + 8} ${y} Td (${escapeText(dateRange)}) Tj ET\n`;

    // Period type
    content += `BT /F1 9 Tf ${leftMargin + 272} ${y} Td (${escapeText(typeName)}) Tj ET\n`;

    // Notes
    if (period.notes) {
      y -= 12;
      content += `BT /F2 7 Tf 0.5 0.5 0.5 rg ${leftMargin + 16} ${y} Td (${escapeText(period.notes.substring(0, 90))}) Tj ET\n`;
      content += `0 0 0 rg\n`;
    }

    // Separator
    y -= 4;
    content += `0.9 0.9 0.9 RG 0.25 w ${leftMargin} ${y} m ${leftMargin + pageWidth} ${y} l S\n`;
    y -= 14;
  }

  y -= 15;

  // Period Definitions section
  if (y < 250) y = 250; // Ensure space
  content += `0.8 0.8 0.8 RG 0.5 w ${leftMargin} ${y} m ${leftMargin + pageWidth} ${y} l S\n`;
  y -= 25;
  content += `BT /F1 14 Tf ${leftMargin} ${y} Td (${escapeText("Period Definitions")}) Tj ET\n`;
  y -= 20;

  const types: PeriodType[] = ["contact", "evaluation", "quiet", "dead"];
  for (const type of types) {
    if (y < 60) break;
    const def = PERIOD_DEFINITIONS[type];
    const color = periodTypeColors[type];

    // Color bar
    content += `${color.r} ${color.g} ${color.b} rg ${leftMargin} ${y - 2} 4 14 re f\n`;
    content += `0 0 0 rg\n`;

    // Title
    content += `BT /F1 10 Tf ${leftMargin + 10} ${y} Td (${escapeText(def.title)}) Tj ET\n`;
    y -= 14;

    // Definition (wrap at ~90 chars)
    const words = def.definition.split(" ");
    let line = "";
    for (const word of words) {
      if ((line + " " + word).length > 95) {
        content += `BT /F2 8 Tf 0.3 0.3 0.3 rg ${leftMargin + 10} ${y} Td (${escapeText(line)}) Tj ET\n`;
        y -= 11;
        line = word;
      } else {
        line = line ? line + " " + word : word;
      }
    }
    if (line) {
      content += `BT /F2 8 Tf 0.3 0.3 0.3 rg ${leftMargin + 10} ${y} Td (${escapeText(line)}) Tj ET\n`;
      y -= 11;
    }
    content += `0 0 0 rg\n`;
    y -= 8;
  }

  // Footer
  y = 30;
  content += `BT /F2 7 Tf 0.5 0.5 0.5 rg ${leftMargin} ${y} Td (${escapeText("Generated by RepMax  |  repmax.io  |  Source: NCAA Division I Recruiting Calendars 2025-26")}) Tj ET\n`;
  content += `BT /F2 7 Tf 0.5 0.5 0.5 rg ${leftMargin + pageWidth - 120} ${y} Td (${escapeText("NCAA is a trademark of the NCAA.")}) Tj ET\n`;

  // ─── Assemble PDF ───────────────────────────────────────────
  const objects: string[] = [];

  // Obj 1: Catalog
  objects.push("1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj");

  // Obj 2: Pages
  objects.push("2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj");

  // Obj 3: Page
  objects.push(
    "3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] " +
    "/Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj"
  );

  // Obj 4: Content stream
  const streamBytes = new TextEncoder().encode(content);
  objects.push(
    `4 0 obj\n<< /Length ${streamBytes.length} >>\nstream\n${content}endstream\nendobj`
  );

  // Obj 5: Font (Helvetica Bold)
  objects.push(
    "5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj"
  );

  // Obj 6: Font (Helvetica)
  objects.push(
    "6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj"
  );

  // Build PDF
  let pdf = "%PDF-1.4\n";
  const offsets: number[] = [];

  for (const obj of objects) {
    offsets.push(pdf.length);
    pdf += obj + "\n";
  }

  const xrefOffset = pdf.length;
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  for (const offset of offsets) {
    pdf += `${offset.toString().padStart(10, "0")} 00000 n \n`;
  }

  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefOffset}\n%%EOF\n`;

  return new TextEncoder().encode(pdf);
}

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const division = (searchParams.get("division") || "FBS").toUpperCase() as "FBS" | "FCS";

  if (division !== "FBS" && division !== "FCS") {
    return NextResponse.json({ error: "Division must be FBS or FCS" }, { status: 400 });
  }

  const pdfBytes = generatePDF(division);

  return new NextResponse(pdfBytes as unknown as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="RepMax_NCAA_${division}_Recruiting_Calendar_2025-26.pdf"`,
      "Content-Length": pdfBytes.length.toString(),
    },
  });
}
