export type BillingMode = 'subscription' | 'payment' | 'free' | 'contact';

export type PricingPlan = {
  name: string;
  slug: string;
  annualSlug?: string;
  monthlyPrice: number;
  annualPrice?: number;
  billingMode: BillingMode;
  features: string[];
  description: string;
  ctaText: string;
  highlighted?: boolean;
  accentColor?: string;
  contactEmail?: string;
  priceLabel?: string;
};

export type PricingSubCategory = {
  id: string;
  label: string;
  plans: PricingPlan[];
  billingNote?: string;
};

export type PricingCategory = {
  id: string;
  label: string;
  icon: string;
  hasToggle: boolean;
  plans: PricingPlan[];
  billingNote?: string;
  subCategories?: PricingSubCategory[];
};

export const pricingCategories: PricingCategory[] = [
  {
    id: 'athletes',
    label: 'Athletes',
    icon: 'sprint',
    hasToggle: true,
    billingNote: 'All plans billed monthly. Cancel anytime. Annual plans save ~17%.',
    plans: [
      {
        name: 'Basic',
        slug: 'athlete-basic',
        monthlyPrice: 0,
        billingMode: 'free',
        description: 'For the casual athlete',
        ctaText: 'Get Started Free',
        features: ['Basic Profile', 'Limited Visibility', 'View Offers'],
      },
      {
        name: 'Premium',
        slug: 'athlete-premium',
        annualSlug: 'athlete-premium-annual',
        monthlyPrice: 14.99,
        annualPrice: 149.90,
        billingMode: 'subscription',
        description: 'For the competitive athlete',
        ctaText: 'Go Premium',
        highlighted: true,
        accentColor: 'primary',
        features: [
          'Enhanced Profile',
          'Priority Visibility',
          'Video Highlights',
          'Direct Messaging',
          'Recruiting Analytics',
        ],
      },
      {
        name: 'Pro',
        slug: 'athlete-pro',
        annualSlug: 'athlete-pro-annual',
        monthlyPrice: 59.99,
        annualPrice: 599.90,
        billingMode: 'subscription',
        description: 'For the elite prospect',
        ctaText: 'Go Pro',
        accentColor: 'accent-green',
        features: [
          'Everything in Premium',
          'AI Film Analysis',
          'RepMax Score',
          'Featured Profile',
          'Verified Badge',
          'Priority Support',
        ],
      },
    ],
  },
  {
    id: 'recruiters',
    label: 'Recruiters',
    icon: 'person_search',
    hasToggle: true,
    billingNote: 'All plans billed monthly. Cancel anytime. Annual plans save ~17%.',
    plans: [
      {
        name: 'Free',
        slug: 'recruiter-free',
        monthlyPrice: 0,
        billingMode: 'free',
        description: 'For casual scouting',
        ctaText: 'Start Free',
        features: ['Basic Search', '10 Searches/Day', 'Public Profiles'],
      },
      {
        name: 'Pro',
        slug: 'recruiter-pro',
        annualSlug: 'recruiter-pro-annual',
        monthlyPrice: 99,
        annualPrice: 990,
        billingMode: 'subscription',
        description: 'For the serious recruiter',
        ctaText: 'Go Pro',
        highlighted: true,
        accentColor: 'primary',
        features: [
          'Full Database Access',
          'Unlimited Search',
          'Advanced Filters',
          'Export CSV',
          'Shortlists',
        ],
      },
      {
        name: 'Team',
        slug: 'recruiter-team',
        annualSlug: 'recruiter-team-annual',
        monthlyPrice: 299,
        annualPrice: 2990,
        billingMode: 'subscription',
        description: 'For the recruiting staff',
        ctaText: 'Get Team',
        accentColor: 'accent-green',
        features: [
          'Everything in Pro',
          '5 Team Seats',
          'Shared Watchlists',
          'Collaboration Tools',
          'Priority Support',
        ],
      },
      {
        name: 'AI',
        slug: 'recruiter-ai',
        annualSlug: 'recruiter-ai-annual',
        monthlyPrice: 399,
        annualPrice: 3990,
        billingMode: 'subscription',
        description: 'For data-driven recruiting',
        ctaText: 'Get AI',
        accentColor: 'accent-purple',
        features: [
          'Everything in Team',
          'AI Prospect Matching',
          'Predictive Analytics',
          'Custom Reports',
          'API Access',
        ],
      },
      {
        name: 'Enterprise',
        slug: 'recruiter-enterprise',
        monthlyPrice: 0,
        billingMode: 'contact',
        description: 'For agencies & media',
        ctaText: 'Contact Sales',
        contactEmail: 'sales@repmax.io',
        features: [
          'Everything in AI',
          'Unlimited Seats',
          'SSO Integration',
          'Dedicated Account Manager',
          'Custom Reporting',
          'SLA',
        ],
      },
    ],
  },
  {
    id: 'events',
    label: 'Events',
    icon: 'event',
    hasToggle: false,
    billingNote: 'One-time purchase per event.',
    plans: [
      {
        name: 'Basic',
        slug: 'event-basic',
        monthlyPrice: 99,
        billingMode: 'payment',
        description: 'For single events',
        ctaText: 'Buy Now',
        features: [
          'Single Event Listing',
          'Basic Registration',
          'Attendee Management',
        ],
      },
      {
        name: 'Standard',
        slug: 'event-standard',
        monthlyPrice: 249,
        billingMode: 'payment',
        description: 'For multi-day events',
        ctaText: 'Buy Now',
        highlighted: true,
        accentColor: 'primary',
        features: [
          'Multi-Day Events',
          'Custom Registration Forms',
          'Payment Collection',
          'Email Notifications',
          'Analytics Dashboard',
        ],
      },
      {
        name: 'Premium',
        slug: 'event-premium',
        monthlyPrice: 499,
        billingMode: 'payment',
        description: 'For tournament organizers',
        ctaText: 'Buy Now',
        accentColor: 'accent-green',
        features: [
          'Everything in Standard',
          'Tournament Brackets',
          'Live Scoring',
          'Streaming Integration',
          'White-Label Branding',
          'Priority Support',
        ],
      },
    ],
  },
  {
    id: 'dashr',
    label: 'Dashr',
    icon: 'speed',
    hasToggle: false,
    plans: [],
    subCategories: [
      {
        id: 'combines',
        label: 'Combines',
        billingNote: 'One-time purchases. No recurring charges.',
        plans: [
          {
            name: 'Standard Combine',
            slug: 'dashr-standard',
            monthlyPrice: 149,
            billingMode: 'payment',
            description: 'NFL-grade laser timing combine',
            ctaText: 'Buy Now',
            features: [
              'Dashr laser timing (NFL-grade)',
              'Verified 40yd / Pro Agility / 3-Cone / Jumps',
              'Printed certificate',
              'Results uploaded to RepMax',
            ],
          },
          {
            name: 'AI-Verified Combine',
            slug: 'dashr-ai',
            monthlyPrice: 199,
            billingMode: 'payment',
            description: 'AI-powered biomechanical analysis',
            ctaText: 'Buy Now',
            highlighted: true,
            accentColor: 'primary',
            features: [
              'Everything in Standard Combine',
              'AI skeletal tracking',
              'Force-velocity profiling',
              'Biomechanical breakdown',
              'Slow-mo video + PDF report',
              '30-day training plan',
              'Leaderboard placement',
            ],
          },
        ],
      },
      {
        id: 'training',
        label: 'Training',
        billingNote: 'One-time purchases. No recurring charges.',
        plans: [
          {
            name: 'Combine Blueprint',
            slug: 'dashr-blueprint',
            monthlyPrice: 79.99,
            billingMode: 'payment',
            description: '3hr technique training session',
            ctaText: 'Buy Now',
            features: [
              '3hr technique training',
              'Dashr baseline + final testing',
              'Position-specific drills',
              'Before/after comparison',
            ],
          },
          {
            name: 'Position-Specific Clinic',
            slug: 'dashr-clinic',
            monthlyPrice: 99,
            billingMode: 'payment',
            description: 'Sport-specific drill session',
            ctaText: 'Buy Now',
            highlighted: true,
            accentColor: 'primary',
            features: [
              'Football / Basketball / Track / Baseball drills',
              'Dashr-verified performance data',
              'Professional coaching',
              'Performance certificate',
            ],
          },
          {
            name: 'Multi-Day Intensive',
            slug: 'dashr-intensive',
            monthlyPrice: 149,
            priceLabel: '$149/day',
            billingMode: 'payment',
            description: 'Multi-day progressive training camp',
            ctaText: 'Buy Now',
            accentColor: 'accent-green',
            features: [
              'Daily Dashr tracking',
              'Progressive performance monitoring',
              'Personalized adjustments',
              'Force-velocity profiling',
              '1-on-1 coaching',
            ],
          },
        ],
      },
      {
        id: 'testing',
        label: 'Testing',
        billingNote: 'On-site professional timing services for teams and programs.',
        plans: [
          {
            name: 'Single Testing Day',
            slug: 'dashr-testing-single',
            monthlyPrice: 750,
            billingMode: 'contact',
            description: 'On-site combine for your team (~$25/athlete)',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            features: [
              'On-site Dashr setup',
              'Up to 30 athletes',
              'Full combine battery',
              'Printed certificates',
              'Team performance report',
            ],
          },
          {
            name: 'Seasonal Package',
            slug: 'dashr-testing-seasonal',
            monthlyPrice: 2200,
            priceLabel: '$2,200',
            billingMode: 'contact',
            description: '3 sessions across the season (~$18/athlete/test)',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            highlighted: true,
            accentColor: 'primary',
            features: [
              '3 sessions (pre / mid / post-season)',
              'Up to 40 athletes per session',
              'Progressive performance tracking',
              'Force-velocity profiling',
              'Season-long analytics',
            ],
          },
          {
            name: 'Multi-Sport Contract',
            slug: 'dashr-testing-contract',
            monthlyPrice: 4500,
            priceLabel: '$4,500/yr',
            billingMode: 'contact',
            description: 'Full-year program for large athletic departments',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            accentColor: 'accent-green',
            features: [
              'Up to 150 athletes',
              '3 testing cycles per year',
              'Sport-specific testing modules',
              'Biometric scanning',
              'Dedicated account manager',
            ],
          },
        ],
      },
      {
        id: 'services',
        label: 'Services',
        billingNote: 'Professional services. Contact us for scheduling and availability.',
        plans: [
          {
            name: 'Biometric Day',
            slug: 'dashr-biometric',
            monthlyPrice: 400,
            billingMode: 'contact',
            description: 'Height/weight/wingspan via BioStation',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            features: [
              'Height / weight / wingspan / reach via BioStation',
              'Up to 40 athletes',
              'Roster data sheet',
              'Recruiting-formatted data',
            ],
          },
          {
            name: 'Sport-Specific Camp',
            slug: 'dashr-sport-camp',
            monthlyPrice: 800,
            priceLabel: '$800/half-day',
            billingMode: 'contact',
            description: '2-3hr sport testing with position drills',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            features: [
              'Up to 25 athletes',
              '2-3hr sport-specific testing',
              'Position drill modules',
              'Individual athlete reports',
            ],
          },
          {
            name: 'Pro-Style Combine',
            slug: 'dashr-pro-combine',
            monthlyPrice: 1200,
            priceLabel: '$1,200',
            billingMode: 'contact',
            description: 'NFL-style combine event for 60 athletes',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            highlighted: true,
            accentColor: 'primary',
            features: [
              'Up to 60 athletes',
              'NFL-style testing battery',
              'Professional 1-3pg reports',
              'Optional college coach invites',
            ],
          },
          {
            name: 'F-V Profiling',
            slug: 'dashr-fv-profiling',
            monthlyPrice: 1500,
            priceLabel: '$1,500',
            billingMode: 'contact',
            description: 'Deep force-velocity analysis for 30 athletes',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            accentColor: 'accent-green',
            features: [
              'Multi-split 40yd (5/10/20/30/40)',
              'Force-velocity profiles',
              'Mechanical deficiency identification',
              'Coach education session',
              'Up to 30 athletes',
            ],
          },
          {
            name: 'Regional Leaderboard',
            slug: 'dashr-leaderboard',
            monthlyPrice: 600,
            priceLabel: '$600/yr',
            billingMode: 'contact',
            description: 'Branded rankings by position and grade',
            ctaText: 'Contact Sales',
            contactEmail: 'sales@repmax.io',
            features: [
              'Branded rankings by position / grade / event',
              'Quarterly updates',
              'Social media assets',
              'Embeddable leaderboard widget',
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'schools',
    label: 'Schools',
    icon: 'school',
    hasToggle: false,
    billingNote: 'Annual subscriptions. Invoice-based billing available for institutions.',
    plans: [
      {
        name: 'Small School',
        slug: 'school-small',
        monthlyPrice: 1500,
        priceLabel: '$1,500/yr',
        billingMode: 'subscription',
        description: '1-2 sports, up to 50 athletes',
        ctaText: 'Get Started',
        features: [
          '1-2 sports supported',
          'Up to 50 athletes',
          'Team dashboard',
          'Basic analytics',
          'Student athlete profiles',
        ],
      },
      {
        name: 'Medium School',
        slug: 'school-medium',
        monthlyPrice: 2500,
        priceLabel: '$2,500/yr',
        billingMode: 'subscription',
        description: '3-5 sports, up to 150 athletes',
        ctaText: 'Get Started',
        highlighted: true,
        accentColor: 'primary',
        features: [
          '3-5 sports supported',
          'Up to 150 athletes',
          'AI roster analysis',
          'Recruiting calendar',
          'Zone intelligence',
          'Includes 1 Free Testing Day',
        ],
      },
      {
        name: 'Large School',
        slug: 'school-large',
        monthlyPrice: 3500,
        priceLabel: '$3,500/yr',
        billingMode: 'subscription',
        description: '6+ sports, 150+ athletes',
        ctaText: 'Get Started',
        accentColor: 'accent-green',
        features: [
          '6+ sports supported',
          '150+ athletes',
          'Full department dashboard',
          'Advanced analytics + reporting',
          'Priority support',
          'Includes Seasonal Testing Package',
        ],
      },
    ],
  },
];
