/**
 * Staging Loader — Loads parsed prospect data into import_prospects_staging
 *
 * Reads from staging-data.json (generated by Python parser) and inserts
 * into Supabase via the JS client.
 *
 * Usage:
 *   npx tsx supabase/import/staging-loader.ts
 *
 * Requires:
 *   NEXT_PUBLIC_SUPABASE_URL (or SUPABASE_URL)
 *   SUPABASE_SERVICE_ROLE_KEY
 */

import { readFileSync } from 'fs';
import { resolve } from 'path';
import { createClient } from '@supabase/supabase-js';

const BATCH_SIZE = 20;

function getSupabaseClient() {
  const url = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    throw new Error('Missing SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY');
  }

  return createClient(url, key, {
    auth: { autoRefreshToken: false, persistSession: false },
  });
}

async function main() {
  console.log('='.repeat(60));
  console.log('STAGING LOADER — Loading prospects into Supabase');
  console.log('='.repeat(60));

  const supabase = getSupabaseClient();

  // Load parsed data
  const dataPath = resolve(__dirname, 'staging-data.json');
  const rows = JSON.parse(readFileSync(dataPath, 'utf-8'));
  console.log(`\nLoaded ${rows.length} rows from staging-data.json`);

  // Check existing count
  const { count: existing } = await supabase
    .from('import_prospects_staging')
    .select('*', { count: 'exact', head: true });
  console.log(`Existing staging rows: ${existing || 0}`);

  let inserted = 0;
  let errors = 0;

  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    const batch = rows.slice(i, i + BATCH_SIZE);

    const { error } = await supabase.from('import_prospects_staging').insert(batch);

    if (error) {
      console.log(`  ✗ Batch ${Math.floor(i / BATCH_SIZE) + 1}: ${error.message}`);
      errors += batch.length;

      // Try one-by-one for this batch
      for (const row of batch) {
        const { error: singleErr } = await supabase
          .from('import_prospects_staging')
          .insert(row);
        if (singleErr) {
          console.log(`    ✗ ${row.full_name}: ${singleErr.message}`);
        } else {
          inserted++;
          errors--;
        }
      }
    } else {
      console.log(`  ✓ Batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} rows`);
      inserted += batch.length;
    }
  }

  // Final count
  const { count: final } = await supabase
    .from('import_prospects_staging')
    .select('*', { count: 'exact', head: true });

  console.log('\n' + '='.repeat(60));
  console.log('STAGING LOAD COMPLETE');
  console.log('='.repeat(60));
  console.log(`Inserted: ${inserted}`);
  console.log(`Errors:   ${errors}`);
  console.log(`Total staging rows: ${final}`);
}

main().catch((err) => {
  console.error('Fatal:', err);
  process.exit(1);
});
